services:
  app:
    build: .
    container_name: tgr_catalog_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      # Ensure SQLite file persists on volume
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    ports:
      - "8000:8000"

  vite:
    image: node:20-alpine
    container_name: tgr_catalog_vite
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true


